### ISSUE TITLE
gps/anemometer

### ISSUE THREAD

**Issue by TangoRom** [kmkingsbury/raspberrypi-weather-station#7]
Hi there. This is a nice project, indeed. Great job.
I just want to save me some time by not building the wind speed and rain collector. Do you think these items will work with the rest of the components you used? (see links below, please):

GPS:
http://www.adafruit.com/product/746

Anemometer:
http://www.adafruit.com/product/1733

Couldn't find anything as for rain collector bucket that comes pre-assembled and to empty itself.

Thank you.

**Comment by kmkingsbury** [comment]
Yes, looks like those will totally work.

There's also these guys to get the whole set without making them. I picked one up:
https://www.sparkfun.com/products/8942
And here:
http://www.kr4.us/weather-meters.html

**Comment by TangoRom** [comment]
Thank you. I'll definitely look into it.
